assignments/urls.py
from django.urls import path
from .import views

app_name = "assignments"

urlpatterns=[
    path("",views.index,name="index"),
    path("delete/",views.delete_task,name="delete"),
    path("task/completed/",views.completed,name="completed"),
    path("register/",views.register,name="register"),
    path("home/",views.home,name="home"),
    path("assignment/<int:ass_id>",views.assignment,name="assignment"),
    path("solutions/<int:ass_id>",views.solutions,name="solution"),
    path("solution/<int:ass_id>",views.Solution_specific,name="single_solution"),
    path("solution/submit/<int:ass_id>",views.submit,name="submit"),
    path("user/logged/in",views.login_manually,name="logged_in"),


    path("logout/",views.logout,name="logout_redirect")
]

elphinites/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("assignments.urls",namespace="main")),
    path('accounts/',include("django.contrib.auth.urls")),

]


urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

assignments/models.py
from django.db import models
from datetime import datetime

from django.contrib.auth.models import User as djangouser

# Create your models here.



class Student(models.Model):
    rollNo = models.IntegerField()
    user = models.OneToOneField(djangouser,null=True,on_delete=models.CASCADE, related_name="student")

    def __str__(self):
        return self.user.username


class Assignment(models.Model):
    title=models.CharField(max_length=80,null=True)
    description=models.CharField(max_length=9999,null=True)
    start_date=models.DateField(auto_now_add=True,null=True)
    duedate = models.DateField(null=True)
    subject = models.CharField(max_length=80,null=True)

    added = models.BooleanField(default=False,)

    def add(self):
        if self.added==False:
            for student in Student.objects.all():
                ass= StudentAssignment(student=student,assignment=self)
                ass.save()
            self.added=True
            self.save()


    @property
    def get_attchments(self):
        return self.attachments.all()

    def __str__(self):
        return self.title

class StudentAssignment(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE,null=True,related_name="assignment")
    assignment = models.ForeignKey(Assignment,on_delete=models.CASCADE,null= True,related_name="studentassignment")
    done=models.BooleanField(default=False)
    complete_date=models.DateField(blank=True,null=True)
    submitted = models.BooleanField(default=False)

    def __str__(self):
        return self.student.user.username + " : " + self.assignment.title

    @property
    def sol_title(self):
        return "Solution of " + self.assignment.title +" by " + self.student.user.username 


    

class solution(models.Model):
    
    image = models.ImageField(blank=True,null=True)
    assignment = models.ForeignKey(StudentAssignment,on_delete=models.CASCADE,null=True,related_name="solution")
    submission_date=models.DateField(auto_now_add=True)

    def __str__(self):
        return "Solution of " + self.assignment.assignment.title +" by " + self.assignment.student.user.username 
    @property
    def title(self):
        return "Solution of " + self.assignment.assignment.title +" by " + self.assignment.student.user.username 


class Attachment(models.Model):
    image = models.ImageField(blank=True,null=True)
    assignment = models.ForeignKey(Assignment,on_delete=models.CASCADE,null=True,related_name="attachments")

    def __str__(self):
        return "Attachment of " + self.assignment.title

assignments/views.py
from django.shortcuts import render,redirect
from .models import*
import datetime
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User as djangouser


# Create your views here.

def index(request,warning="",error="",success =""):
    if request.user.is_authenticated:
        for ass in Assignment.objects.all():
            ass.add()
        try:
            student = request.user.student
        except:
            if request.user.is_superuser:
                student = Student(rollNo=0,user=request.user)
                student.save()
            else:
                return home(request)
        assignments = student.assignment.all()
        return render(request,"assignments/index.html",{
            "assignments": assignments,
            "error":error,
            "warning":warning,
            "success":success
        })
    else:
        return home(request)


def delete_task(request):
    if request.method=="POST":
        if "rmtask" in request.POST:
            task_id= int(request.POST["rmtask"])
            if task_id in StudentAssignment.objects.values_list("id",flat=True):
                today=datetime.datetime.now()
                task=StudentAssignment.objects.get(pk=task_id)
                task.complete_date=today.date()
                task.done=True
                task.save()


    return redirect("/")


def completed(request):
    if request.user.is_authenticated:
        student = request.user.student
        assignments = student.assignment.all()
        return render(request,"assignments/history.html",{
            "assignments":assignments
        })

    redirect("/")
        
         
def register(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            P = request.POST
            if "username" in P and "password1" in P and "password2" in P and "email" in P and "roll_no" in P:
                print("working")
                username = P['username']
                password = P['password1']
                confirmPassword =P['password2']
                email = P["email"] 
                roll_no = P["roll_no"]

                try:
                    testuser = djangouser.objects.get(username=username)
                    if testuser:
                        return render(request,"registration/register.html",{
                        "error":"Username unavailable"
                        })
                except:
                    pass
                try :
                    testuser = djangouser.objects.get(email=email)
                    if testuser:
                        return render(request,"registration/register.html",{
                        "error":"Email already registered"
                        })
                except:
                    pass
                if password == confirmPassword:
                    
                    newuser = djangouser.objects.create(username=username,password=password,email=email)
                    newuser.save()
                    student = Student(rollNo=roll_no, user = newuser)
                    student.save()
                    newuser.save()

                    login(request,newuser)
                    for assess in Assignment.objects.all():
                        newss = StudentAssignment(student=student,assignment=assess)
                        newss.save()
                    return redirect('/')
                return render(request,"registration/register.html",{
                    "error":"password is not same as confirm passowrd"
                })
            return render(request,"registration/register.html",{
                "error":"Invalid credentials"
            })
            
        return render(request,"registration/register.html")
    
    return index(request,warning="You have already logged in!")
    

def login_manually(request):
    if not request.user.is_authenticated :
        if request.method =="POST":
            if "username" in request.POST and "password" in request.POST:
                username = request.POST["username"]
                password = request.POST["password"]

                try:
                    user = djangouser.objects.get(username=username)
                except:
                    return home(request,error="Invalid Username")


                if authenticate(request,username=username,password=password):
                    login(request,user)
                    return redirect("/")

                if password==user.password:
                    login(request,user)
                    return redirect("/")
                return home(request,error="invalid password")
            
        return redirect("/accounts/login/")
    return index(request)

    

def home(request,error="",general=""):
    if request.user.is_authenticated:
        return index(request,error="You have already logged in!")
    else:
        context={
            "error":error,
            "general":general
        }
        return render(request,"registration/login_signup.html",context)


def logout(request):
    if request.user.is_authenticated:
        return index(request,error="couldn't log out")
    return home(request,general="Logged out succesfully")


def assignment(request,ass_id):
    if request.user.is_authenticated:
        task =StudentAssignment.objects.get(pk=ass_id)
        return render(request,"assignments/assignment.html",{
            "assignment":task
        })

    return home(request,error="You haven't logged in yet!")


def solutions(request,ass_id):
    if request.user.is_authenticated:
        task =StudentAssignment.objects.get(pk=ass_id).assignment.studentassignment.all()
        ss = StudentAssignment.objects.get(pk=ass_id)
        return render(request,"assignments/solutions.html",{
            "assignments":task,
            "ss":ss
        })

    return home(request,error="You haven't logged in yet!")


def Solution_specific(request,ass_id):
    if request.user.is_authenticated:
        task =StudentAssignment.objects.get(pk=ass_id)
        solutions = task.solution.all()
        date = task.solution.first().submission_date
        return render(request,"assignments/solution.html",{
            "assignment":task,
            "solutions":solutions,
            "date":date
        })

    else:
        return home(request,error="You haven't logged in yet!")


def submit(request,ass_id):
    if request.user.is_authenticated:
        if StudentAssignment.objects.get(pk=ass_id).submitted==False:
            if request.method =="GET":
                if "n" in request.GET and int(request.GET["n"])<21:
                    n=request.GET["n"]
                    return render(request,"assignments/submit.html",{
                        "n":n,
                        "range":range(int(n)),
                        "ass_id":ass_id
                        })
                else:
                    return render(request,"assignments/submit.html",{
                        "ass_id":ass_id
                    })

            else:
                print("yessssssss4444",end="\n\n\n")
                P= request.POST
                if "n" in P:
                    print(int(P["n"]))
                    
                    assignment = StudentAssignment.objects.get(pk=ass_id)
                    if "img0" in request.FILES:
                        for i in range(int(P["n"])):
                            img = "img" + str(i)
                            if img in request.FILES:
                                print("yessssssss",end="\n\n\n")
                                image= request.FILES[img]
                                print(image)
                                Solution = solution(assignment=assignment)
                                Solution.save()


                                image_name= "solution"+str(assignment.id) +"_"+ str(Solution.id)+".jpeg"
                                savefile(image,image_name)
                                
                                Solution.image=image_name
                                Solution.save()
                        assignment.submitted=True
                        assignment.save()
                return redirect(("/solution/submit/"+str(ass_id)))

        return index(request,error="You have already submitted your solution")
    return home(request,error="You haven't logged in yet!")

def savefile(f,filename):
    with open('static/images/'+ filename, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

assignments/templates/assignments/assignment.html
{% extends 'assignments/layout.html' %}

{% block content %} 

<br><br>
<div class="container bg-light ">
    <div class="col-lg-10 bg-light " >
        <div class="row  shadow p-3 mb-5  rounded" style="text-align: left;">
            <h1 style="text-align: center;">ASSIGNMENT</h1>
            <h4>Title : <strong>{{assignment.assignment.title}}</strong></h4>
            <br>
            <h4>Subject : <strong>{{assignment.assignment.subject}}</strong></h4>
            <br>
            <h4>Duedate : <strong>{{assignment.assignment.duedate}}</strong></h4>
            <br>
            <h4>Posted on : <strong>{{assignment.assignment.start_date}}</strong></h4>
            <br>
            <h4><strong>Description:</strong> {{assignment.assignment.description}}</h4>
        </div>


        <div class="row  shadow p-3 mb-5  rounded" style="text-align: left;">
            <h1 style="text-align: center;">ATTACHMENTS</h1>
            {% for attachment in assignment.assignment.get_attchments %}
                <img src="{{attachment.image.url}}" alt="attachment">
            {% endfor %}
        </div>
    </div>
</div>



<div class="row" >
    <div class="col-lg-6 justify-content-center">
        <br>
        <a href="{% url 'main:index' %}"><button style="border: 1px transparent;border-radius: 15px;"  type="button" class="btn link-button btn-primary">View ALL Assignments</button></a>
    </div>
    <div class="col-lg-6 justify-content-center">
        <br>
        {% if not assignment.submitted %}
        <a href="{% url 'main:submit' assignment.id %}"><button style="border: 1px transparent;border-radius: 15px;"  type="button" class="btn link-button btn-primary">Submit Your Solutions</button></a>
        {% else %}
        <a href="{% url 'main:single_solution' assignment.id %}"><button style="border: 1px transparent;border-radius: 15px;"  type="button" class="btn link-button btn-success">View Your Solutions</button></a>
        {% endif %}

    </div>
    
</div>

{% endblock %}

assignments/templates/assignments/history.html
{% extends 'assignments/layout.html' %}

{% block content %} 

<script>
    function delete_task(id){
        var taskid="#task"+String(id)
        var formid="#form"+String(id)
        document.querySelector(taskid).className="text-decoration-line-through"
        document.querySelector(formid).submit()
    }
</script>
<br><br>
<div class="container ">
    <div class="col-lg-8 bg-secondary  col-md-10  shadow p-3 mb-5  rounded" >
        <div class="row">
            <hr>
            <table class=" table table-secondary ">
                <tr class="table-dark">
                    <th  class="table-dark">COMPLETED TASKS</th>
                    <th class="table-dark">START DATE</th>
                    <th class="table-dark">END DATE</th>
                </tr>
                {% if assignments %}
                    {% for task in assignments reversed %}
                        {% if task.done %}
                            <tr class="table-secondary" >
                                <td style="text-align: left;" class="table-secondary">{{task.assignment.title}}</td>
                                <td class="table-secondary">{{task.assignment.start_date}}</td>
                                <td class="table-secondary">{{task.complete_date}}</td>
                            </tr>
                    
                        {% endif %}
                    {% endfor %} 
                {% endif %}
                
            </table>
            <hr>
        </div>
    </div>
</div>



<div style="text-align: center;">
    <a href="{% url 'main:index' %}"><button style="border: 1px transparent;border-radius: 15px;"  type="button" class="btn link-button btn-primary">View All Assignments</button></a>
</div>

{% endblock %}

assignments/templates/assignments/index.html
{% extends 'assignments/layout.html' %}

{% block content %} 


<br><br>
<div class="container" >
    <div class="col-lg-8 bg-secondary  col-md-10  shadow p-3 mb-5  rounded">
        {% if assignments %}
            {% for task in assignments reversed %}
                {% if not task.done %}
                    <hr>
                    <div class="row">
                        <div class="col">
                            <form id="form{{task.id}}" action="{% url 'main:delete' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-check">
                                    <input class="form-check-input c{{task.id}}" name="rmtask" onclick="event_add('{{task.id}}')" type="checkbox" value="{{task.id}}" id="flexCheckDefault">
                                    <p1  style="float: left;" id="task{{task.id}}">{{task.assignment.title}}</p1> 
                                    <a href="{% url 'main:assignment' task.id %}"><button style="float:right;" type="button" class="btn btn-primary">view assignment</button></a>
                                    <a href="{% url 'main:solution' task.id %}"><button style="float:right;margin-right: 2px;" type="button" class="btn btn-primary">view Solutions</button></a>
                                    
                                </div>
                            </form>  
                                
                        </div>
                    </div>
                    
                {% endif %}
            {% endfor %} 
            <hr>
            <div class="row " style="display: none;" id="removebtn" >
                <div id="success-alert">
                  <div class="alert alert-success " role="alert">
                    Are you sure you have completed the assignment?
                    <button type="button" class="btn btn-success" id="remove"  aria-label="Close">YESS</button>
                    <button type="button" class="btn-close"  onclick="remove_alert('#removebtn')" aria-label="Close"></button>
                    
                  </div>
            </div>
            
        {% endif %}
        <div id="empty" style="display: none;" class="row">
            <div class="col">

                <div class="form-check task">
                <form>
                        <label class="form-check-label" for="flexCheckDefault">
                        Woohooo !! You have no assignment right now!
                        </label>
                        <hr>
                    </div>
                </form>
            </div>
        </div>
    </div>

    

</div>
<div style="text-align: center;">
    <a href="{% url 'main:completed' %}"><button style="border: 1px transparent;border-radius: 15px;"  type="button" class="btn link-button btn-success">Completed Tasks</button></a>
</div>
<script>
    a= document.getElementsByClassName('form-check');
    if(a.length==1){
        
        document.getElementById("empty").style.display="block";
    }
    
</script>

{% endblock %}

assignments/templates/assignments/layout.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.82.0">
    <title>Todo App</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/jumbotron/">

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://unpkg.com/ionicons@5.4.0/dist/ionicons.js"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
   

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'style.css' %}">

    
  </head>
<body class="bg-dark">
    
    <main >
    <div class="container py-4">
        
        <header class="pb-3 mb-4 border-bottom  ">
          {% if user.is_authenticated %}
          <div class="row">
            <a href="/" class="d-flex align-items-center col-10 text-white text-decoration-none">
                <svg xmlns='http://www.w3.org/2000/svg' width="40" height="32" class="me-2" class='ionicon' viewBox='0 0 512 512'><title>Code Working</title><circle cx='256' cy='256' r='26'/><circle cx='346' cy='256' r='26'/><circle cx='166' cy='256' r='26'/><path fill='none' stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' stroke-width='32' d='M160 368L32 256l128-112M352 368l128-112-128-112'/></svg>
                <span class="fs-4">ELPHINITES</span>
                
            </a>
            
            <div class="col-2 text-white">
              <a href="{% url 'logout' %}">
                <ion-icon id="logout" name="log-out-outline"></ion-icon>
                <p6 style="font-size: 10px;float: left;">logout</p6>
              </a>
            </div>
            
          </div>
          {% else %}
          <a href="/" class="d-flex align-items-center  text-white text-decoration-none">
            <svg xmlns='http://www.w3.org/2000/svg' width="40" height="32" class="me-2" class='ionicon' viewBox='0 0 512 512'><title>Code Working</title><circle cx='256' cy='256' r='26'/><circle cx='346' cy='256' r='26'/><circle cx='166' cy='256' r='26'/><path fill='none' stroke='currentColor' stroke-linecap='round' stroke-linejoin='round' stroke-width='32' d='M160 368L32 256l128-112M352 368l128-112-128-112'/></svg>
            <span class="fs-4">ELPHINITES</span>
            
          </a>
          {% endif %}
        </header>
          
            
        

        
        {% if success %}
        <div class="row" >
          <div id="success-alert">
            <div class="alert alert-success " role="alert">
              {{success}}
              <button type="button" class="btn-close"  onclick="remove_alert('#success-alert')" aria-label="Close"></button>
              
            </div>
          </div>
      {% endif %}
      {% if general %}
          <div id="compose-alert" >
            <div class="alert alert-primary"  role="alert">
              {{general}}
              <button type="button right-float" class="btn-close" onclick="remove_alert('#compose-alert')"  aria-label="Close"></button>
            </div>
          </div class="row" style="margin-left:20%;">
      {% endif %}
      {% if error %}
          <div id="error-alert">
            <div class="alert alert-danger display-block" role="alert">
              {{error}}
              <button type="button right-float" class="btn-close" onclick="remove_alert('#error-alert')"  aria-label="Close"></button>
            </div>
          </div>
      {% endif %}
      {% if warning %}
          <div id="warning-alert">
            <div class="alert alert-warning display-block" role="alert">
              {{warning}}
              <button type="button right-float" class="btn-close" onclick="remove_alert('#warning-alert')" aria-label="Close"></button>
            </div>
          </div>
      {% endif %}
        
        {% block content %}

        {% endblock %}
        
        <footer class="pt-3 mt-4 text-white text-muted border-top">
        &copy; 2021 Sarfaraj Ansari
        </footer>
    </div>
    </main>
    <script src="{% static 'script.js' %}"></script>

        
    </body>
</html>

assignments/templates/assignments/solution.html
{% extends 'assignments/layout.html' %}

{% block content %} 

<br><br>
<div class="container bg-light ">
    <div class="col-lg-10 bg-light " >
        <div class="row  shadow p-3 mb-5  rounded" style="text-align: left;">
            <h1 style="text-align: center;">ASSIGNMENT</h1>
            <h4>Title : <strong>{{assignment.assignment.title}}</strong></h4>
            <br>
            <h4>Subject : <strong>{{assignment.assignment.subject}}</strong></h4>
            <br>
            <h4>Posted on : <strong>{{date}}</strong></h4>
            <br>
            <h4><strong>Description:</strong> {{assignment.assignment.description}}</h4>
        </div>


        <div class="row  shadow p-3 mb-5  rounded" style="text-align: left;">
            <h1 style="text-align: center;">SOLUTION BY {{assignment.student.user.username}}</h1>
            {% for attachment in solutions %}
                <img src="{{attachment.image.url}}" alt="attachment">
            {% endfor %}
        </div>
    </div>
</div>



<div style="text-align: center;">
    <a href="{% url 'main:assignment' assignment.id %}"><button style="border: 1px transparent;border-radius: 15px;"  type="button" class="btn link-button btn-primary">View assignment</button></a>
</div>

{% endblock %}

assignments/templates/assignments/solutions.html
{% extends 'assignments/layout.html' %}

{% block content %} 


<br><br>
<div class="container" >
    <div class="col-lg-8 bg-secondary  col-md-10  shadow p-3 mb-5  rounded">
            {% for task in assignments %}
                {% if task.submitted %}
                    <hr>
                    <div class="row">
                        <div class="col form-check">
                            <p1 style="float: left;"> {{task.sol_title}} </p1>
                            <a href="{% url 'main:single_solution' task.id %}"><button style="float:right;" type="button" class="btn btn-primary">view solution</button></a>
                        </div>
                    </div>
                {% endif %}

            {% endfor %} 
            <hr>
            
        <div id="empty" style="display: none;" class="row">
            <div class="col">

                <div class="form-check task">
                <form>
                        <label class="form-check-label" for="flexCheckDefault">
                        No solution available right now! <br>
                        </label>
                        <hr>
                    </div>
                </form>
            </div>
        </div>
    </div>

    
    
</div>

{% if not ss.submitted %}
<div style="text-align: center;" class="text-white">
    Would you like to submit yours to help your friends by submitting your solution??<br>
    <a href="{% url 'main:submit' ss.id %}"><button type="button" class="btn btn-primary justify-content-center">submit your solution</button></a>
</div>
{% endif %}
<script>
    function delete_task(id){
        var taskid="#task"+String(id)
        var formid="#form"+String(id)
        document.querySelector(taskid).className="text-decoration-line-through"
        document.querySelector(formid).submit()
    }
    a= document.getElementsByClassName('form-check');
    if(a.length==1){
        
        document.getElementById("empty").style.display="block";
    }

    
</script>

{% endblock %}

assignments/templates/assignments/submit.html
{% extends 'assignments/layout.html' %}

{% block content %} 


<br><br>
<div class="container" >
    <div class="col-lg-8 bg-secondary  col-md-10  shadow p-3 mb-5  rounded">

        <hr>
        {% if n %}
        <form method="POST" action="{% url 'main:submit' ass_id %} " enctype="multipart/form-data">
            <div class="row justify-content-center">
                {% csrf_token %}
                {% for i in range %}
                <div class="input-group mb-3">
                    <label class="input-group-text" for="inputGroupFile01">Image {{forloop.counter}}</label>
                    <input type="file" required name="img{{i}}" class="form-control" id="inputGroupFile01">
                </div>
                {% endfor %}
                <input type="hidden" required name="n" value="{{n}}">
                
                <input type="submit" class="btn btn-success w-50">
                    
            </div>
        </form> 
        {% else %}

        <form method="GET" action="{% url 'main:submit' ass_id %} ">
            <div class="row justify-content-center">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="inputGroup-sizing-default">Number of images in your assignment</span>
                    <input type="number" name="n" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                </div>
                <input type="submit" class="btn btn-success w-50">
                    
            </div>
        </form> 
        
        {% endif %}


    </div>

    

</div>


{% endblock %}